# Generated by Django 2.0.3 on 2018-03-22 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0006_auto_20180319_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='application',
            name='recommended_by',
        ),
        migrations.AddField(
            model_name='application',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recommender', to=settings.AUTH_USER_MODEL),
        ),
    ]
