# Generated by Django 2.0.3 on 2018-03-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20180322_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='prefix',
            field=models.PositiveIntegerField(default=0, help_text='In days'),
        ),
        migrations.AlterField(
            model_name='application',
            name='suffix',
            field=models.PositiveIntegerField(default=0, help_text='In days'),
        ),
    ]
