# Generated by Django 2.0.3 on 2018-03-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20180323_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='availLTC',
            new_name='avail_ltc',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='typeOfLeave',
            new_name='type_of_leave',
        ),
    ]
