# Generated by Django 2.0.3 on 2018-03-22 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180319_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
